
HF_TOKEN="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"
GROQ_API_KEY="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"
TAVILY_API_KEY="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"
SERPER_API_KEY="faeaec1a6b7b7804c99fe744cb6254a61f99e1cc"
